language: python


python:
  - "2.7_with_system_site_packages"


#env:
#  - LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib


install:
  - "bash ./.travis.sh"
  - "pip install -r requirements.txt"


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


script:
  - py.test
